// 导出盒子几何体类 - 用于创建立方体和长方体
export * from "./BoxGeometry.js";
// 导出胶囊几何体类 - 用于创建胶囊形状（圆柱体两端加半球）
export * from "./CapsuleGeometry.js";
// 导出圆形几何体类 - 用于创建圆形平面
export * from "./CircleGeometry.js";
// 导出圆锥几何体类 - 用于创建圆锥形状
export * from "./ConeGeometry.js";
// 导出圆柱几何体类 - 用于创建圆柱形状
export * from "./CylinderGeometry.js";
// 导出十二面体几何体类 - 用于创建正十二面体
export * from "./DodecahedronGeometry.js";
// 导出边缘几何体类 - 用于从现有几何体提取边缘线段
export * from "./EdgesGeometry.js";
// 导出挤出几何体类 - 用于将2D形状挤出成3D几何体
export * from "./ExtrudeGeometry.js";
// 导出二十面体几何体类 - 用于创建正二十面体
export * from "./IcosahedronGeometry.js";
// 导出车床几何体类 - 用于通过旋转2D轮廓创建3D几何体
export * from "./LatheGeometry.js";
// 导出八面体几何体类 - 用于创建正八面体
export * from "./OctahedronGeometry.js";
// 导出平面几何体类 - 用于创建矩形平面
export * from "./PlaneGeometry.js";
// 导出多面体几何体类 - 用于创建各种多面体的基类
export * from "./PolyhedronGeometry.js";
// 导出环形几何体类 - 用于创建环形（甜甜圈形状的平面）
export * from "./RingGeometry.js";
// 导出形状几何体类 - 用于从2D形状创建几何体
export * from "./ShapeGeometry.js";
// 导出球体几何体类 - 用于创建球形
export * from "./SphereGeometry.js";
// 导出四面体几何体类 - 用于创建正四面体
export * from "./TetrahedronGeometry.js";
// 导出圆环几何体类 - 用于创建圆环（甜甜圈形状）
export * from "./TorusGeometry.js";
// 导出圆环结几何体类 - 用于创建圆环结形状
export * from "./TorusKnotGeometry.js";
// 导出管道几何体类 - 用于沿着路径创建管道形状
export * from "./TubeGeometry.js";
// 导出线框几何体类 - 用于从现有几何体创建线框表示
export * from "./WireframeGeometry.js";
